

export const countries = [
  {
    'country': 'India',
    'states': [
      'Arunachal Pradesh',
      'Assam ',
      'Bihar ',
      'Goa ',
      'Gujarat ',
      'Haryana ',
      'Himachal Pradesh',
      'Jammu & Kashmir',
      'Karnataka ',
      'Kerala ',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya ',
      'Mizoram ',
      'Nagaland',
      'Orissa',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Tripura',
      'Uttar Pradesh ',
      'West Bengal',
      'Chhattisgarh',
      'Uttarakhand',
      'Jharkhand',
      'Andhra Pradesh',

    ]
  },
  {
    'country': 'USA',
    'states': [
      'Alabama ',
      'Alaska ',
      'Arizona ',
      'Arkansas ',
      'California ',
      'Colorado ',
      'Connecticut ',
      'Delaware ',
      'Florida ',
      'Georgia ',
      'Hawaii ',
      'Idaho ',
      'Illinois',
      'Indiana ',
      'Iowa ',
      'Kansas ',
      'Kentucky ',
      'Louisiana ',
      'Maine ',
      'Maryland ',
      'Massachusetts ',
      'Michigan ',
      'Minnesota ',
      'Mississippi ',
      'Missouri ',
      'Montana',
      'Nebraska ',
      'Nevada ',
      'New Hampshire ',
      'New Jersey ',
      'New Mexico ',
      'New York ',
      'North Carolina ',
      'North Dakota ',
      'Ohio ',
      'Oklahoma ',
      'Oregon ',
      'Pennsylvania',
      'Rhode Island ',
      'South Carolina ',
      'South Dakota ',
      'Tennessee ',
      'Texas ',
      'Utah ',
      'Vermont ',
      'Virginia ',
      'Washington ',
      'West Virginia ',
      'Wisconsin ',
      'Wyoming',
    ]
  },
  {
    'country': 'Canada',
    'states': [
      'Alberta (AB)',
      'British Columbia (BC)',
      'Prince Edward Island (PE)',
      'Manitoba (MB)',
      'New Brunswick (NB)',
      'Nova Scotia (NS)',
      'Ontario (ON)',
      'Quebec (QC)',
      'Saskatchewan (SK)',
      'Newfoundland and Labrador (NL)',

    ]

  },
  {
    'country': 'France',
    'states': [
      'Alsace',
      'Aquitaine',
      'Auvergne',
      'Brittany',
      'Burgundy',
      'Centre',
      'Champagne-Ardenne',
      'Franche-Comté',
      'Île-de-France',
      'Languedoc-Roussillon',
      'Limousin',
      'Lorraine',
      'Lower Normandy',
      'Midi-Pyrénées',
      'Nord-Pas-de-Calais',
      'Pays de la Loire',
      'Picardy',
      'Poitou-Charentes',
      'Provence-Alpes-Côte d Azur',
      'Rhône-Alpes',
      'Upper Normandy',
      'Corsica',

    ]
  },
  {
    'country': 'Germany',
    'states': [
      'Baden-Württemberg BW',
      'Bavaria BY',
      'Berlin BE',
      'Brandenburg',
      'Bremen HB',
      'Hamburg',
      'Hesse HE',
      'Lower Saxony NI',
      'Mecklenburg-Vorpommern MV',
      'North Rhine-Westphalia',
      'Rhineland-Palatinate RP',
      'Saarland SL',
      'Saxony SN',
      'Saxony-Anhalt ST',
      'Schleswig-Holstein SH',
      'Thuringia TH',

    ]
  }

];
